# Generated by Django 5.0.3 on 2024-03-14 09:31

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=156)),
                ('text', django_ckeditor_5.fields.CKEditor5Field()),
                ('slug', models.CharField(blank=True, max_length=156, unique=True)),
                ('time_to_create', models.DateTimeField(auto_now_add=True)),
                ('time_to_update', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_announces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('tanks', 'Tanks'), ('healers', 'Healers'), ('dd', 'DD'), ('traders', 'Traders'), ('guildmasters', 'Guildmasters'), ('questgivers', 'Questgivers'), ('blacksmiths', 'Blacksmiths'), ('leatherworkers', 'Leatherworkers'), ('potion_masters', 'Potions Masters'), ('spellmasters', 'Spellmasters')], default='tanks', max_length=56)),
                ('slug', models.SlugField(blank=True, max_length=56)),
                ('announce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='callboard.announce')),
            ],
        ),
        migrations.AddField(
            model_name='announce',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announces', to='callboard.category'),
        ),
        migrations.CreateModel(
            name='Respond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=256)),
                ('time_to_create', models.DateTimeField(auto_now_add=True)),
                ('time_to_update', models.DateTimeField(auto_now=True)),
                ('announce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responds', to='callboard.announce')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_responds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
